default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  # database: <%= ENV["POSTGRES_DB"] %>
  # username: <%= ENV.fetch("PGUSER", "sham") %>
  # password: <%= ENV["POSTGRES_PASSWORD"] %>
  # host: <%= ENV["POSTGRES_HOST"] %>
  # port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  database: rails_book_app_test

production:
  primary: &primary
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  cable:
    <<: *primary
